workspace/ruby/first_app/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :boards
end

workspace/ruby/first_app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

workspace/ruby/first_app/app/models/board.rb
class Board < ApplicationRecord
	validates :title, presence: true, length: { in: 4..127 }
	validates :editor, presence: true, length: { in: 1..30 }
end

workspace/ruby/first_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

workspace/ruby/first_app/app/controllers/boards_controller.rb
class BoardsController < ApplicationController
	def index
		@boards = Board.all
	end

	def new
		@board = Board.new
	end

	def create
		@board = Board.new(params_board)
		if @board.save
			redirect_to boards_url
		else
			render :new
		end
	end

	def show
		@board = Board.find(params[:id])
	end

	def edit
		@board = Board.find(params[:id])
	end

	def update
		@board = Board.find(params[:id])
		@board.update_attributes(params_board)
		redirect_to board_url(@board)
	end

	def destroy
		@board = Board.find(params[:id])
		@board.destroy
		redirect_to boards_url
	end

	private

	def params_board
		params.require(:board).permit(:title, :editor)
	end
end

workspace/ruby/first_app/app/helpers/application_helper.rb
module ApplicationHelper
end

workspace/ruby/first_app/app/views/boards/edit.html.erb
<%= link_to @board.title, board_path(@board) %>
<hr>
<h1>Boards#edit</h1>
<%= form_for @board do |f| %>
	タイトル: <%= f.text_field :title %> <br>
	作成者名: <%= f.text_field :editor %> <br>
	<%= f.submit %>
<% end %>

workspace/ruby/first_app/app/views/boards/index.html.erb
<h1>2chクローン</h1>
<%= link_to "スレッド新規作成", new_board_path %>
<hr>
<% @boards.each do |board| %>
	<%= link_to board.title, board_path(board) %><br />
<% end %>

workspace/ruby/first_app/app/views/boards/new.html.erb
<%= link_to "スレッド一覧に戻る", boards_path %>
<% if @board.errors.any? %>
	<ul>
		<% @board.errors.full_messages.each do | error | %>
			<li><%= error %></li>
		<% end %>
	</ul>
<% end %>
<hr>
<h1>Boards#new</h1>
<%= form_for @board, method: :post do |f| %>
	タイトル: <%= f.text_field :title %> <br>
	作成者名: <%= f.text_field :editor %> <br>
	<%= f.submit %>
<% end %>

workspace/ruby/first_app/app/views/boards/show.html.erb
<%= link_to 'スレッド一覧に戻る', boards_path %>
<hr>
<h1><%= @board.title %></h1>
<%= link_to "タイトルを編集する", edit_board_path(@board) %>
<%= link_to "削除する", board_path(@board), method: :delete, data: { confirm: "本当に？" } %>
<hr>

workspace/ruby/first_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FirstApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>